// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsctiOW8P1AF0MNpDuo2E3_5Bd_fCEAXE',
    appId: '1:814320157041:web:844bfc95867724e1ceb6d0',
    messagingSenderId: '814320157041',
    projectId: 'p2p-exchange-b475c',
    authDomain: 'p2p-exchange-b475c.firebaseapp.com',
    storageBucket: 'p2p-exchange-b475c.firebasestorage.app',
    measurementId: 'G-QJLHHYVXG0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB11kYg3aTOM5-u1nRFYSRGdEGdpIJzQPA',
    appId: '1:814320157041:android:4ad076fdbe96367fceb6d0',
    messagingSenderId: '814320157041',
    projectId: 'p2p-exchange-b475c',
    storageBucket: 'p2p-exchange-b475c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClTJS3dQ4nW3-YdNcLeDPVqGrBJOdtBFo',
    appId: '1:814320157041:ios:95eac0c29e53632cceb6d0',
    messagingSenderId: '814320157041',
    projectId: 'p2p-exchange-b475c',
    storageBucket: 'p2p-exchange-b475c.firebasestorage.app',
    iosBundleId: 'com.example.p2pExchange',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClTJS3dQ4nW3-YdNcLeDPVqGrBJOdtBFo',
    appId: '1:814320157041:ios:95eac0c29e53632cceb6d0',
    messagingSenderId: '814320157041',
    projectId: 'p2p-exchange-b475c',
    storageBucket: 'p2p-exchange-b475c.firebasestorage.app',
    iosBundleId: 'com.example.p2pExchange',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCsctiOW8P1AF0MNpDuo2E3_5Bd_fCEAXE',
    appId: '1:814320157041:web:a9bdbb930288a9c4ceb6d0',
    messagingSenderId: '814320157041',
    projectId: 'p2p-exchange-b475c',
    authDomain: 'p2p-exchange-b475c.firebaseapp.com',
    storageBucket: 'p2p-exchange-b475c.firebasestorage.app',
    measurementId: 'G-MY263Y0LH6',
  );
}
